homework3: merge request
made-mlops-2022/denis_shibitov pull request #3
Opened 2022-12-04 19:45 UTC by y-met

2022-12-07 08:39 UTC, bulaevvi requested changes
Нижние скриншоты нормальные, но на верхнем (общем) видно, что даги падали (судя по красным кружочкам). Надо разобраться, почему они падали, и добиться такого результата, чтобы все выполнялось нормально

Обратите внимание, что в приведенном мною дискордовском примере падений не было https://discord.com/channels/681511874449244211/1011956997790380123/1049258596866727946

2022-12-07 10:25 UTC, bulaevvi commented
Прикрепите пожалуйста скриншоты прямо здесь, в комментариях, чтобы не сбивалась дата сабмита и не тратить времени на поиск файлов

2022-12-08 10:24 UTC, y-met commented
> Прикрепите пожалуйста скриншоты прямо здесь, в комментариях, чтобы не сбивалась дата сабмита и не тратить времени на поиск файлов

Здравствуйте.

Да, даги падали. Причины: какие-то в процессе выполнения дз  + как минимум все падали один раз чтобы проверить отправление сообщения о падении DAG:
"Дополнительная часть:
...
10. Настройте alert в случае падения дага https://www.astronomer.io/guides/error-notifications-in-airflow (+3 доп балла) --- Выполнено (+3)"

По поводу скриншота - думал вполне достаточно, что видно что последний запуск каждого DAG выполнен успешно.
Сейчас почистил журнал от старых ошибок + сделал ран всех дагов.

2022-12-08 10:24 UTC, y-met commented
![Screenshot from 2022-12-08 13-14-51](https://user-images.githubusercontent.com/52403787/206422867-5cb52a16-a5f0-4a78-87e4-3362ee901e2b.png)

2022-12-09 04:28 UTC, bulaevvi approved these changes
Итого 37 баллов. Делайте merge

2022-12-10 15:05 UTC, merged